name: BazarTrack
description: "On-demand groceries. Real-time tracking. Instant payments."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  flutter_svg:
  syncfusion_flutter_charts: ^30.2.5
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900